resources:
  - name: repo_pipe
    type: GitRepo
    configuration:
      gitProvider: vijay_github
      path: vijayreddy1991/jfrog
      
pipelines:
  - name: demo_installer
    steps:
      - name: Spin_up_AWS
        type: Bash
        configuration:
          affinityGroup: debain 
          priority: 0
          timeoutSeconds: 50000
#           nodePool: ubuntu_16
          environmentVariables:
            env1: value1
            env2: value2
          integrations:
            - name: aws_keys
          inputResources:
            - name: repo_vijay
          runtime:       
            type: image     #<image/host>
            image:
              custom:
                name: drydock/u16
                tag: master
        execution:
          onExecute: 
            - pwd
            - terraform --version
            - printenv
            - pushd $res_repo_vijay_resourcePath
            - terraform init            
            - ls -la
            - PWD=$(pwd)
            - echo PWD=$PWD
            - replace_envs $PWD/keys.tfvar
            - terraform apply -auto-approve -var-file="$PWD/keys.tfvar"
            - terraform output vijay_ip
            - vijay_ip_address=$(terraform output vijay_ip)
            - echo "$vijay_ip_address"
            - terraform output bindu_ip
            - bindu_ip_address=$(terraform output bindu_ip)
            - echo "$bindu_ip_address"
            - add_pipeline_variables bindu_ip_address=$bindu_ip_address            
            - add_pipeline_variables vijay_ip_address=$vijay_ip_address
            - add_pipeline_files $PWD/terraform.tfstate jfrog_pipeline
            - popd

      - name: Run_installer_ubuntu
        type: Bash
        configuration:
          affinityGroup: debain
          priority: 0
          timeoutSeconds: 50000
#           nodePool: ubuntu_16
          environmentVariables:
            env1: value1
            env2: value2
          integrations:
            - name: bindu_pem 
            - name: ART_keys
            - name: art
          inputSteps:
            - name: Spin_up_AWS_machine
          inputResources:
            - name: repo_vijay            
          runtime:       
            type: image     #<image/host>
            image:
              custom:
                name: drydock/u16
                tag: master
        execution:
          onExecute:
            - printenv
            - pushd $res_repo_pipe_resourcePath
            - PWD=$(pwd)
            - echo $PWD
            - replace_envs $PWD/pipeline_installer.sh
            - cat $PWD/pipeline_installer.sh
            - echo "$int_bindu_pem_key" > bindu.pem
            - cat $PWD/bindu.pem
            - echo $vijay_ip_address
            - chmod 777 "$PWD"/pipeline_installer.sh
            - chmod 777 "$PWD"/test.sh
            - sudo chmod 600 "$PWD"/bindu.pem
            - cp "$PWD"/bindu.pem ~/.ssh/
            - cat ~/.ssh/bindu.pem
            - which ssh
            - scp -i ~/.ssh/bindu.pem $PWD/pipeline_installer.sh test.sh ubuntu@$vijay_ip_address:~
            - ssh -i ~/.ssh/bindu.pem ubuntu@$vijay_ip_address ls
            - ssh -i ~/.ssh/bindu.pem ubuntu@$vijay_ip_address "sudo ./pipeline_installer.sh"
            - ssh -i ~/.ssh/bindu.pem ubuntu@$vijay_ip_address "sudo ./test.sh"

      - name: Run_installation_centos
        type: Bash
        configuration:
          affinityGroup: debain
          priority: 0
          timeoutSeconds: 50000
          environmentVariables:
            env1: value1
            env2: value2
          integrations:
            - name: bindu_pem 
            - name: ART_keys
            - name: art  
          inputSteps:
            - name: Spin_up_AWS_machine
          inputResources:
            - name: repo_pipe   
          runtime:       
            type: image     #<image/host>
            image:
              custom:
                name: drydock/u16
                tag: master
        execution:
          onExecute:
            - printenv
            - pushd $res_repo_pipe_resourcePath
            - PWD=$(pwd)
            - echo $PWD
            - replace_envs $PWD/pipeline_centos.sh
            - cat $PWD/pipeline_centos.sh
            - echo "$int_bindu_pem_key" > bindu.pem
            - cat $PWD/bindu.pem
            - echo $bindu_ip_address
            - chmod 777 "$PWD"/pipeline_centos.sh
            - chmod 777 "$PWD"/test.sh
            - sudo chmod 600 "$PWD"/bindu.pem
            - cp "$PWD"/bindu.pem ~/.ssh/
            - cat ~/.ssh/bindu.pem
            - which ssh
            - scp -i ~/.ssh/bindu.pem $PWD/pipeline_centos.sh test.sh centos@$bindu_ip_address:~
            - ssh -i ~/.ssh/bindu.pem centos@$bindu_ip_address ls
            - ssh -i ~/.ssh/bindu.pem centos@$bindu_ip_address "sudo ./pipeline_centos.sh"
            - ssh -i ~/.ssh/bindu.pem centos@$bindu_ip_address "sudo ./test.sh"

      - name: Destroy_AWS_machines
        type: Bash
        configuration:
          affinityGroup: debain 
          priority: 0
          timeoutSeconds: 50000
#           nodePool: ubuntu_16
          environmentVariables:
            env1: value1
            env2: value2
          integrations:
            - name: aws_keys
          inputSteps:
            - name: Run_installer_ubuntu
            - name: Run_installation_centos
          inputResources:
            - name: repo_pipe
          runtime:       
            type: image     #<image/host>
            image:
              custom:
                name: drydock/u16
                tag: master
        execution:
          onExecute:
            - echo "test3"  
            - pushd $res_repo_pipe_resourcePath
            - echo $PWD
            - echo "$vijay_ip_address"
            - terraform init
            - replace_envs $PWD/keys.tfvar
            - restore_pipeline_files jfrog_pipeline $PWD/terraform.tfstate
            - terraform destroy -auto-approve -var-file="$PWD/keys.tfvar"
            - popd


